# Generated by Django 4.2.3 on 2023-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='activ_ver',
            field=models.BooleanField(default=False, verbose_name='Активная версия'),
        ),
    ]
