# Generated by Django 4.2.3 on 2023-08-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_is_published_permission', 'Can cancel product publication'), ('can_change_desc_permission', 'Can change product description'), ('can_change_category_permission', 'Can change product category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
